spring.application.name=lynas-slash-admin-server
spring.profiles.active=local
server.port=8080
spring.jackson.time-zone=Asia/Shanghai
management.endpoints.web.exposure.include=health,info
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.global-config.db-config.logic-delete-field=deleted
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0
